#POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv pyenv anaconda root_indicator dir)
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time date battery)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs)
#POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{black} $(print_icon 'LEFT_SUBSEGMENT_SEPARATOR') %F{black}"
POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{white} $(printf $'\ue0b1') %F{white}"
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"
POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true

POWERLEVEL9K_OS_ICON_BACKGROUND="white"
POWERLEVEL9K_OS_ICON_FOREGROUND="blue"

POWERLEVEL9K_BATTERY_ICON='\ue801'
POWERLEVEL9K_BATTERY_LOW_THRESHOLD='15'
POWERLEVEL9K_BATTERY_VERBOSE=false
#POWERLEVEL9K_TIME_FORMAT="%D{%R \ue184 %a %d. %b}"
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_TIME_FOREGROUND="white"
POWERLEVEL9K_TIME_BACKGROUND="black"
POWERLEVEL9K_DATE_FORMAT="%D{%d. %b}"
POWERLEVEL9K_IGNORE_TERM_COLORS=true

